export const ITEMS_LIST_SUCCESS = 'ITEMS_LIST_SUCCESS';
export const ITEMS_LIST_ERROR = 'ITEMS_LIST_ERROR';

export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';
export const ITEM_DETAILS_ERROR = 'ITEM_DETAILS_ERROR';
